server:
  contextPath: /api/dev
  port: 8888
---
environment: dev
---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/avalokkumar/microservice-cloud-config.git
  application:
    name: ConfigServer